sudo: required
services: 
  - docker
before_install: 
  - docker build -t maorrocky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maorrocky/react-test npm test -- -- coverage

after_success:
  - docker build -t maorrocky/multi-client ./client
  - docker build -t maorrocky/multi-nginx ./nginx
  - docker build -t maorrocky/multi-server ./server
  - docker build -t maorrocky/multi-worker ./worker

  #log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maorrocky/multi-client
  - docker push maorrocky/multi-nginx
  - docker push maorrocky/multi-server
  - docker push maorrocky/multi-worker